spring.application.name=api-gateway
server.port=${PORT}

spring.config.import=optional:file:.env[.properties]

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# Auth Service Route
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth-service/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1

# User Service Route
spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/user-service/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1

# Post Service Route
spring.cloud.gateway.server.webflux.routes[2].id=post-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://post-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/post-service/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=1

# Like Service Route
spring.cloud.gateway.server.webflux.routes[3].id=like-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://like-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/like-service/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=StripPrefix=1

# Comment Service Route
spring.cloud.gateway.server.webflux.routes[4].id=comment-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://comment-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/comment-service/**
spring.cloud.gateway.server.webflux.routes[4].filters[0]=StripPrefix=1

# Chat Service Route
spring.cloud.gateway.server.webflux.routes[5].id=chat-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://chat-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/chat-service/**
spring.cloud.gateway.server.webflux.routes[5].filters[0]=StripPrefix=1